### ISSUE TITLE
Custom .gitmodules file.

### ISSUE THREAD

**Issue by andrew2net** [metanorma/lapidist#1]
Could we have a separated releas-tool gem to use it with custom .gitmodules file?

**Comment by ronaldtse** [comment]
Yes, as you can see, the release tool has been moved to the Lapidist repository. However, the release tool has hard coded the “metanorma/“ GitHub org namespace. We need to make it customizable per GRM using YAML configuration files. 

Ie. From now on, the metanorma-release repo is used for releasing gems, by using the lapidist gem inside.

**Comment by CAMOBAP** [comment]
@andrew2net @ronaldtse now lapidist don't rely on .gitmodules you just need to pass `-p <path_to_gem_root_directory>`

Soon I will start work on https://github.com/metanorma/lapidist/issues/5

**Comment by ronaldtse** [comment]
@camobap795 that’s great. Could you also add a help command to show this?
