### ISSUE TITLE
Implement scripts to support release flow

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/lapidist#2]
Today Metanorma spans over 50 gems. Changes to underlying gems, such as [`metanorma`](https://github.com/metanorma/metanorma) can cause many of the downstream gems to need upgrading.

In order to simplify this procedures, a set of build scripts in this repository need to be implemented.

The requirements are listed in https://github.com/metanorma/metanorma-release/blob/master/README.adoc .

In fact, this flow has to be flexible because it also applies to `relaton` and its dependent gems (`relaton-*`)

**Comment by CAMOBAP** [comment]
@ronaldtse I think we are ready to close this one because the tool with actions described here https://github.com/metanorma/lapidist/issues/2#issuecomment-500920811 are implemented

**Comment by ronaldtse** [comment]
Got it. Have we now generalized it for Relaton too?
