### ISSUE TITLE
How to run commands?

### ISSUE THREAD

**Issue by andrew2net** [metanorma/lapidist#6]
@CAMOBAP795 I made a repo for relaton gems releasing https://github.com/relaton/relaton-release
But I don't have `exe/mn-release` to run? Can you help?

**Comment by CAMOBAP** [comment]
recently we moved release-tool to separate repo https://github.com/metanorma/lapidist (and renamed mn-release to lapidist) please check the readme there and `exe/lapidist help`

Actually you don't need git submodules repo to be able use this tool

It will be enough to have a directory which will contain all gem repos

Let me know if you have more questions

**Comment by ronaldtse** [comment]
@andrew2net you just need to run `bundle exec lapidist` directly to use the gem. The command options in the gem aren't implemented properly so you can't use `lapidist help` etc, but if you issue the right commands it could work.

**Comment by andrew2net** [comment]
@CAMOBAP795 I got the error:
```
bundle exec lapidist
/Users/andrej/.rvm/gems/ruby-2.4.0/bundler/gems/lapidist-ca378a027dad/exe/lapidist:6:in `require_relative': cannot load such file -- /Users/andrej/.rvm/gems/ruby-2.4.0/bundler/gems/lapidist-ca378a027dad/lib/metanorma/release/tool/cli/command (LoadError)
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bundler/gems/lapidist-ca378a027dad/exe/lapidist:6:in `<top (required)>'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/lapidist:23:in `load'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/lapidist:23:in `<main>'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```
I tried to comment `/exe/lapidist:6` but it needs `Metanorma::Release::Tool::Cli::Command`. I don't see it in any dependency. Suppose it is in `../lib/metanorma/release/tool/cli/command` file, but I don't have it.

**Comment by ronaldtse** [comment]
@andrew2net I've added a Gemfile and Gemfile.lock for lapidist in relaton-release. This is the output now, it works:

```sh
bundle exec lapidist start
Error: missing argument: Missing -b/--branch [value]
```
